In [2]:
import numpy as np

In [3]:
a = np.array([1,2,3,4])

In [4]:
a

array([1, 2, 3, 4])

In [5]:
print(a)

[1 2 3 4]


In [7]:
b = np.arange(10)

In [8]:
print(b)

[0 1 2 3 4 5 6 7 8 9]


In [9]:
a.ndim

1

In [10]:
a.shape

(4,)

In [12]:
len(a)


4

In [13]:
len(b)

10

In [18]:
c = np.array([[0,1,2],[3,4,5]])

In [19]:
c

array([[0, 1, 2],
       [3, 4, 5]])

In [20]:
c.ndim

2

In [21]:
c.shape

(2, 3)

In [22]:
len(c)

2

In [25]:
d = np.array([[[0,1],[2,3]],[[4,5],[5,6]]])

In [26]:
d.ndim

3

In [27]:
d.shape

(2, 2, 2)

In [28]:
len(d)

2

In [30]:
e = np.arange(5,10)

In [31]:
print(e)

[5 6 7 8 9]


In [32]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [33]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [34]:
np.linspace(0,10,4)

array([ 0.        ,  3.33333333,  6.66666667, 10.        ])

In [35]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [36]:
np.zeros((3))

array([0., 0., 0.])

In [38]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [40]:
np.zeros((3,3,3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [54]:
k = np.eye(3,3)

In [53]:
k

array([[1., 0.],
       [0., 1.],
       [0., 0.]])

In [55]:
np.eye(3,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [60]:
n= np.diag((1,2,3,4,5))

In [61]:
np.diag(n)

array([1, 2, 3, 4, 5])

In [63]:
a = np.random.rand(4)

In [64]:
a

array([0.63410007, 0.49025521, 0.71429994, 0.82624146])

In [65]:
np.random.randn(5)

array([-0.35512386, -0.88406915,  0.83372118, -0.40646339,  0.37840876])

In [67]:
r = np.arange(10)
r

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [68]:
r.dtype

dtype('int64')

In [69]:
a = np.arange(10,dtype = 'float64')

In [70]:
a

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [71]:
t = np.zeros((3,4))

In [72]:
t.dtype

dtype('float64')

In [73]:
s = np.array(['a','b','c'])

In [74]:
s

array(['a', 'b', 'c'], dtype='<U1')

In [75]:
s.dtype

dtype('<U1')

In [77]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [78]:
a[5]

5

In [79]:
a[:]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [80]:
a[1:]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [82]:
a[3:]

array([3, 4, 5, 6, 7, 8, 9])

In [83]:
a[:2]

array([0, 1])

In [86]:
a[3:9]

array([3, 4, 5, 6, 7, 8])

In [87]:
a[1:7:2]

array([1, 3, 5])

In [89]:
a[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [90]:
c = np.array([[0,1,2],[3,4,5]])

In [95]:
c[1,2]

5

In [96]:
u = np.arange(10)

In [97]:
v = u[::2]

In [99]:
np.shares_memory(v,u)

True

In [100]:
v[0]=10
v

array([10,  2,  4,  6,  8])

In [101]:
u

array([10,  1,  2,  3,  4,  5,  6,  7,  8,  9])

In [104]:
i = np.arange(10)

In [109]:
j = i[::2].copy()
j

array([0, 2, 4, 6, 8])

In [107]:
np.shares_memory(i,j)

False

In [113]:
j[0] = 10

In [114]:
j

array([10, 10,  4,  6,  8])

In [115]:
i

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [125]:
p = np.random.randint(0,20,15)

In [126]:
p

array([ 6, 16, 10,  6, 19, 15,  0,  1, 14, 10,  1, 17, 17,  1, 17])

In [130]:
mask = (p%2==0)

In [131]:
m = p[mask]

In [132]:
m

array([ 6, 16, 10,  6,  0, 14, 10])

In [133]:
p[mask] = -1

In [134]:
p

array([-1, -1, -1, -1, 19, 15, -1,  1, -1, -1,  1, 17, 17,  1, 17])

In [136]:
t = np.arange(0,100,10)

In [138]:
t[[2,3,4]]

array([20, 30, 40])

In [140]:
t[[9,7]] = -200

In [141]:
t

array([   0,   10,   20,   30,   40,   50,   60, -200,   80, -200])

In [147]:
a = np.array([1,2,3])+1

In [148]:
np.array([2,4])**2

array([ 4, 16])

In [149]:
b = np.ones(4)+1


In [150]:
b

array([2., 2., 2., 2.])

In [152]:
c = np.diag((1,2,3))

In [153]:
c * c

array([[1, 0, 0],
       [0, 4, 0],
       [0, 0, 9]])

In [155]:
a  = np.array([1,2,3,4])

In [156]:
b = np.array([4,5,6,7])


In [160]:
a == b

array([False, False, False, False])

In [161]:
np.array_equal(a,b)

False

In [163]:
b = np.array([0,1,1,1],dtype='bool')
a = np.array([1,1,0,1],dtype='bool')

In [165]:
np.logical_or(a,b)

array([ True,  True,  True,  True])

In [166]:
a  = np.random.randint(10,100,5)

In [167]:
a

array([87, 77, 99, 59, 75])

In [168]:
np.sin(a)

array([-0.82181784,  0.99952016, -0.99920683,  0.63673801, -0.38778164])

In [169]:
a + np.array([1,2])

ValueError: operands could not be broadcast together with shapes (5,) (2,) 

In [170]:
np.sum(a)

397

In [171]:
np.max(a)

99

In [173]:
np.min(a)

59

In [175]:
x = np.array([[1,2,3],[4,5,6]])

In [177]:
x.sum(axis=0)#coloumn

array([5, 7, 9])

In [178]:
x.sum(axis=1)

array([ 6, 15])

In [179]:
a.argmin()

3

In [181]:
a.argmax()

2

In [182]:
np.all([True,True,False])

False

In [183]:
np.any([True,False,False])

True

In [184]:
a = np.zeros((50,50))

In [185]:
np.any(a==0)

True

In [186]:
np.any(a!=0)

False

In [187]:
np.all(a==0)

True

In [192]:
x = np.array([1, 2, 3, 1])
y = np.array([[1, 2, 3], [5, 6, 1]])
x.mean()

1.75

In [194]:
np.median(x)

1.5

In [196]:
np.median(y,axis=1)

array([2., 5.])

In [198]:
np.median(y,axis=0)

array([3., 4., 2.])

In [199]:
np.std(y,axis=0)

array([2., 2., 1.])

In [200]:
data = np.loadtxt('populations.txt')

In [201]:
data

array([[ 1900., 30000.,  4000., 48300.],
       [ 1901., 47200.,  6100., 48200.],
       [ 1902., 70200.,  9800., 41500.],
       [ 1903., 77400., 35200., 38200.],
       [ 1904., 36300., 59400., 40600.],
       [ 1905., 20600., 41700., 39800.],
       [ 1906., 18100., 19000., 38600.],
       [ 1907., 21400., 13000., 42300.],
       [ 1908., 22000.,  8300., 44500.],
       [ 1909., 25400.,  9100., 42100.],
       [ 1910., 27100.,  7400., 46000.],
       [ 1911., 40300.,  8000., 46800.],
       [ 1912., 57000., 12300., 43800.],
       [ 1913., 76600., 19500., 40900.],
       [ 1914., 52300., 45700., 39400.],
       [ 1915., 19500., 51100., 39000.],
       [ 1916., 11200., 29700., 36700.],
       [ 1917.,  7600., 15800., 41800.],
       [ 1918., 14600.,  9700., 43300.],
       [ 1919., 16200., 10100., 41300.],
       [ 1920., 24700.,  8600., 47300.]])

In [202]:
data.T

array([[ 1900.,  1901.,  1902.,  1903.,  1904.,  1905.,  1906.,  1907.,
         1908.,  1909.,  1910.,  1911.,  1912.,  1913.,  1914.,  1915.,
         1916.,  1917.,  1918.,  1919.,  1920.],
       [30000., 47200., 70200., 77400., 36300., 20600., 18100., 21400.,
        22000., 25400., 27100., 40300., 57000., 76600., 52300., 19500.,
        11200.,  7600., 14600., 16200., 24700.],
       [ 4000.,  6100.,  9800., 35200., 59400., 41700., 19000., 13000.,
         8300.,  9100.,  7400.,  8000., 12300., 19500., 45700., 51100.,
        29700., 15800.,  9700., 10100.,  8600.],
       [48300., 48200., 41500., 38200., 40600., 39800., 38600., 42300.,
        44500., 42100., 46000., 46800., 43800., 40900., 39400., 39000.,
        36700., 41800., 43300., 41300., 47300.]])

In [203]:
y ,h ,l ,c = data.T

In [204]:
y

array([1900., 1901., 1902., 1903., 1904., 1905., 1906., 1907., 1908.,
       1909., 1910., 1911., 1912., 1913., 1914., 1915., 1916., 1917.,
       1918., 1919., 1920.])

In [205]:
p = data[:,1:]

In [206]:
p

array([[30000.,  4000., 48300.],
       [47200.,  6100., 48200.],
       [70200.,  9800., 41500.],
       [77400., 35200., 38200.],
       [36300., 59400., 40600.],
       [20600., 41700., 39800.],
       [18100., 19000., 38600.],
       [21400., 13000., 42300.],
       [22000.,  8300., 44500.],
       [25400.,  9100., 42100.],
       [27100.,  7400., 46000.],
       [40300.,  8000., 46800.],
       [57000., 12300., 43800.],
       [76600., 19500., 40900.],
       [52300., 45700., 39400.],
       [19500., 51100., 39000.],
       [11200., 29700., 36700.],
       [ 7600., 15800., 41800.],
       [14600.,  9700., 43300.],
       [16200., 10100., 41300.],
       [24700.,  8600., 47300.]])

In [207]:
p.std(axis = 0) #0  = column 

array([20897.90645809, 16254.59153691,  3322.50622558])

In [208]:
np.argmax(p,axis=1)

array([2, 2, 0, 0, 1, 1, 2, 2, 2, 2, 2, 2, 0, 0, 0, 1, 2, 2, 2, 2, 2])

In [212]:
a = np.array([[1,2,3],[4,5,6]])

In [213]:
a.ravel()

array([1, 2, 3, 4, 5, 6])

In [215]:
a.T.ravel()

array([1, 4, 2, 5, 3, 6])

In [216]:
b = a.ravel()

In [217]:
b 

array([1, 2, 3, 4, 5, 6])

In [218]:
b = b.reshape((2,3))

In [220]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [226]:
b = b.reshape((3,2))

In [227]:
b

array([[1, 2],
       [3, 4],
       [5, 6]])

In [228]:
b[0,1] = 100

In [229]:
b


array([[  1, 100],
       [  3,   4],
       [  5,   6]])

In [230]:
a

array([[  1, 100,   3],
       [  4,   5,   6]])

In [231]:
z = np.array([1,2,3])

In [ ]:
z 